server:
  port: 8888
    
spring:
  application:
    name: laohei-share-system-service
  datasource:
    url: jdbc:mysql://xx.xx.xx.xx:3306/laohei_website_system_db?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xxxxxx
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  redis:
    port: 6379
    host: xx.xx.xx.xx
    password: xxxxxx
    
# 设置 springboot 默认文件上传大小 10MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    

      
# Ftp 文件服务信息
ftp.server: xx.xx.xx.xx
ftp.port: xx
ftp.userName: xxxxxxxxx
ftp.userPassword: xxxxxxxxx
ftp.basePath: /upload
ftp.imageUrl: https://laohei.vip/xxxxxx/upload/

# 图片保存最大不超过 10M
laohei.image.max-size: 10485760
